### PR TITLE
[FIX] cetmix_tower_server: Fix unsupported ssh key format

### PR DESCRIPTION
**Pull request by GabbasovDinar**
This commit fixes the following issue:

Steps to reproduce
------------------
- Create a new ed25519 ssh key and add it to both Tower and remote server
- Click "Test connection"

Expected result
---------------
- Connection test passes with success

Current result
--------------
- SSH execute command error unpack requires a buffer of 4 bytes

Task: 4004

### CODE REVIEW

**Review by ivs-cetmix — APPROVED** [review]
Code review LGTM

**Review by Aldeigja — APPROVED** [review]
Functional LGTM

**Comment by CetmixGitDrone** [comment]
This PR looks fantastic, let's merge it!
Prepared branch [14.0-dev-ocabot-merge-pr-123-by-ivs-cetmix-bump-nobump](https://github.com/cetmix/cetmix-tower/commits/14.0-dev-ocabot-merge-pr-123-by-ivs-cetmix-bump-nobump), awaiting test results.

**Comment by CetmixGitDrone** [comment]
Congratulations, your PR was merged at 75f1d8111b5ac9cc83d25b6fd9345e1c6770c924. Thanks a lot for contributing to cetmix. ❤️

**Pull request merged**
