### PR TITLE
[14.0] cetmix_tower_server: file template YAML export/import 

### PR DESCRIPTION
**Pull request by ivs-cetmix**
Rename module
----------------

Rename module from `cetmix_tower_server_yaml` into `cetmix_tower_yaml`. This is done because YAML support is a generic feature which might be used not only for the `cetmix_tower_server` module only but for other ones added in the future.

Add YAML support for file templates
------------------------------------

Export/import file templates using YAML format.

### CODE REVIEW

**Review by GabbasovDinar — APPROVED** [review]

**Review by Aldeigja — APPROVED** [review]
Functional LGTM

**Comment by CetmixGitDrone** [comment]
Hey, thanks for contributing! Proceeding to merge this for you.
Prepared branch [14.0-dev-ocabot-merge-pr-111-by-ivs-cetmix-bump-nobump](https://github.com/cetmix/cetmix-tower/commits/14.0-dev-ocabot-merge-pr-111-by-ivs-cetmix-bump-nobump), awaiting test results.

**Comment by CetmixGitDrone** [comment]
Congratulations, your PR was merged at 15c9ab6708f00f967010ef78c92e48e6e2c78252. Thanks a lot for contributing to cetmix. ❤️

**Pull request merged**
