### PR TITLE
[14.0][IMP] cetmix_tower_yaml: Secret value check

### PR DESCRIPTION
**Pull request by ivs-cetmix**
When exporting a key the secret value is replaced with the mask. This is done to prevent leaking sensitive data during export. However this may create an issue when the same file is imported back. Because if this mask still remains in the imported file it will overwrite the actual secret value.

This commit prevents this from happening by checking the secret value before creating or updating a key.
If the mask is still present in the file as a value an error is raised.

Task: 4119

## Summary by CodeRabbit

- **New Features**
	- Enhanced validation for sensitive fields during record creation and updates, preventing the use of predefined secret value masks for both `secret_value` and `ssh_password`.
	
- **Bug Fixes**
	- Introduced validation checks that raise errors when invalid secret values are used, ensuring data integrity.

- **Tests**
	- Added new test methods to validate the handling of secret values and SSH passwords, confirming that invalid values are appropriately rejected.
	- Updated test imports to reflect changes in the testing structure.
	- Removed outdated test cases that are no longer needed.

### CODE REVIEW

**Review by GabbasovDinar — APPROVED** [review]

**Comment by CetmixGitDrone** [comment]
This PR has the `approved` label and has been created more than 5 days ago. It should therefore be ready to merge by a maintainer (or a PSC member if the concerned addon has no declared maintainer). 🤖

**Review by Aldeigja — APPROVED** [review]
Functional LGTM

**Review by hoangtrann — APPROVED** [review]
Code LGTM

**Comment by CetmixGitDrone** [comment]
Congratulations, PR rebased to [14.0-dev](https://github.com/cetmix/cetmix-tower/commits/14.0-dev).

**Comment by CetmixGitDrone** [comment]
Hey, thanks for contributing! Proceeding to merge this for you.
Prepared branch [14.0-dev-ocabot-merge-pr-153-by-ivs-cetmix-bump-nobump](https://github.com/cetmix/cetmix-tower/commits/14.0-dev-ocabot-merge-pr-153-by-ivs-cetmix-bump-nobump), awaiting test results.

**Comment by CetmixGitDrone** [comment]
Congratulations, your PR was merged at 0abee73ee0840434a7f0557e8b0e24c2c2bcfb3f. Thanks a lot for contributing to cetmix. ❤️

**Pull request merged**
