### PR TITLE
[14.0][IMP] t3995 cetmix_tower_server: references in tags

### PR DESCRIPTION
**Pull request by dessanhemrayev**
This commit adds references to tags for easier export/import and action referencing.

Changes
- Inherit from cx.tower.reference.mixin
- Remove field
- Add reference fields to tag views, including search view
- Update documentation to reflect new reference fields in tags

Task: 3995

### CODE REVIEW

**Review by Aldeigja — APPROVED** [review]
Functional LGTM

**Review by ivs-cetmix — APPROVED** [review]
/ocabot merge nobump

**Comment by CetmixGitDrone** [comment]
What a great day to merge this nice PR. Let's do it!
Prepared branch [14.0-dev-ocabot-merge-pr-119-by-ivs-cetmix-bump-nobump](https://github.com/cetmix/cetmix-tower/commits/14.0-dev-ocabot-merge-pr-119-by-ivs-cetmix-bump-nobump), awaiting test results.

**Comment by CetmixGitDrone** [comment]
Congratulations, your PR was merged at f2e3b15b742f9e87aa19ca5cea045c2bbc99e3f2. Thanks a lot for contributing to cetmix. ❤️

**Pull request merged**
