### PR TITLE
[14.0][IMP] cetmix_tower_server: 'readonly' field, many2one restrict, shared cmd/plans

### PR DESCRIPTION
**Pull request by norlinhenrik**
This PR has 3 commits:

**1. A record may be readonly and gray in lists**

Standard commands, flight plans, file tamplates, variables and global variable values may be managed e.g. by Odoo modules. To these 5 models, this commit adds a 'readonly' field and makes sure that 'readonly' data records are readonly and gray in list views.

**2. Restrict deleting a record referenced by many2one**

Deleting a record may delete related records only in these cases:
- Delete flight plan -> Delete related lines
- Delete flight plan line -> Delete related line actions
- Delete flight plan log -> Delete related command logs
- Delete server -> Delete related files, keys and variable values

**3. Show shared commands and plans by default**

Optional, set system parameter `cetmix_tower_server.any_server` = 1

### CODE REVIEW

**Comment by CetmixGitDrone** [comment]
@Aldeigja The rebase process failed, because command `git rebase origin/14.0-dev` failed with output:
```
Rebasing (1/4)
Auto-merging cetmix_tower_server/__manifest__.py
Auto-merging cetmix_tower_server/models/cx_tower_command.py
Auto-merging cetmix_tower_server/models/cx_tower_file_template.py
Auto-merging cetmix_tower_server/models/cx_tower_plan.py
Auto-merging cetmix_tower_server/models/cx_tower_variable.py
Auto-merging cetmix_tower_server/models/cx_tower_variable_value.py
CONFLICT (content): Merge conflict in cetmix_tower_server/models/cx_tower_variable_value.py
Auto-merging cetmix_tower_server/views/cx_tower_command_view.xml
Auto-merging cetmix_tower_server/views/cx_tower_file_template_view.xml
Auto-merging cetmix_tower_server/views/cx_tower_plan_view.xml
Auto-merging cetmix_tower_server/views/cx_tower_server_view.xml
CONFLICT (content): Merge conflict in cetmix_tower_server/views/cx_tower_server_view.xml
Auto-merging cetmix_tower_server/views/cx_tower_variable_value_view.xml
Auto-merging cetmix_tower_server/views/cx_tower_variable_view.xml
error: could not apply 16e5a68... [IMP] cetmix_tower_server: A record may be readonly and gray in lists
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 16e5a68... [IMP] cetmix_tower_server: A record may be readonly and gray in lists

```

**Comment by norlinhenrik** [comment]
@Aldeigja I have fixed the conflicts. When I push, I get an access error. Do I still have access to push to cetmix-tower?

**Comment by ivs-cetmix** [comment]
@norlinhenrik this repo is now public so you should fork it and open a new PR directly from your fork.

**Pull request closed without merging**
