### PR TITLE
[FIX] cetmix_tower: Fix ssh key defenition

### PR DESCRIPTION
**Pull request by GabbasovDinar**
Before this commit
------------------

- Incorrect definition of SSH key type

After this commit
-----------------

- The SSH key type is detected correctly

Task: 4014

### CODE REVIEW

**Review by Aldeigja — APPROVED** [review]
Functional LGTM

**Comment by CetmixGitDrone** [comment]
On my way to merge this fine PR!
Prepared branch [14.0-dev-ocabot-merge-pr-128-by-ivs-cetmix-bump-nobump](https://github.com/cetmix/cetmix-tower/commits/14.0-dev-ocabot-merge-pr-128-by-ivs-cetmix-bump-nobump), awaiting test results.

**Review by ivs-cetmix — APPROVED** [review]
LGTM

**Comment by CetmixGitDrone** [comment]
Congratulations, your PR was merged at cb7c2b820a7ccd7d7700e936819d52cfa1372599. Thanks a lot for contributing to cetmix. ❤️

**Pull request merged**
