### PR TITLE
[14.0][IMP] cetmix_tower_server Improve helpers

### PR DESCRIPTION
**Pull request by ivs-cetmix**
- Commands: expose special 'tower' variable to Python commands. This is a shortcut to the `env['cetmix.tower']`
- cetmix.tower: helper functions to set and get variable values for server

### CODE REVIEW

**Review by Aldeigja — APPROVED** [review]
Functional LGTM
Please fix commit message

**Comment by CetmixGitDrone** [comment]
Congratulations, PR rebased to [14.0-dev](https://github.com/cetmix/cetmix-tower/commits/14.0-dev).

**Review by GabbasovDinar — APPROVED** [review]

**Comment by CetmixGitDrone** [comment]
On my way to merge this fine PR!
Prepared branch [14.0-dev-ocabot-merge-pr-99-by-ivs-cetmix-bump-nobump](https://github.com/cetmix/cetmix-tower/commits/14.0-dev-ocabot-merge-pr-99-by-ivs-cetmix-bump-nobump), awaiting test results.

**Comment by CetmixGitDrone** [comment]
Congratulations, your PR was merged at afa98d3b519f7bb69de7c0671bdc231ada801855. Thanks a lot for contributing to cetmix. ❤️

**Pull request merged**
