### PR TITLE
[14.0] [IMP]  cetmix_tower_server: command log access

### PR DESCRIPTION
**Pull request by Aldeigja**
Restrict access to command log:
User: can see only log records he created.
Manager: + can see all log records for servers he has access to.
Root: can see all records.

### CODE REVIEW

**Review by ivs-cetmix — APPROVED** [review]
Code review LGTM

**Review by Bearnard21 — APPROVED** [review]
Functional LGTM

**Review by ivs-cetmix — CHANGES_REQUESTED** [review]

**Comment by CetmixGitDrone** [comment]
@Aldeigja The rebase process failed, because command `git rebase origin/14.0-dev` failed with output:
```
Rebasing (1/9)
Rebasing (2/9)
Auto-merging cetmix_tower_server/tests/__init__.py
CONFLICT (content): Merge conflict in cetmix_tower_server/tests/__init__.py
error: could not apply 6af9be2... [IMP] cetmix_tower_server: added tests for cetmix tower server command log
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 6af9be2... [IMP] cetmix_tower_server: added tests for cetmix tower server command log

```

**Review by norlinhenrik — APPROVED** [review]
I tested with 3 servers and 3 users, and the access restrictions work.

I was not able to test `('create_uid', '=', user.id)` for a Tower User, since I couldn't run a command as a user due to a [path restriction](https://github.com/cetmix/cetmix-tower/blob/14.0-dev/cetmix_tower_server/wizards/cx_tower_command_execute_wizard.py#L33).
image

**Comment by Aldeigja** [comment]
> I tested with 3 servers and 3 users, and the access restrictions work.
> 
> I was not able to test `('create_uid', '=', user.id)` for a Tower User, since I couldn't run a command as a user due to a [path restriction](https://github.com/cetmix/cetmix-tower/blob/14.0-dev/cetmix_tower_server/wizards/cx_tower_command_execute_wizard.py#L33).

Hi @norlinhenrik we've fixed this issue please test  if you have opportunity.

**Review by ivs-cetmix — APPROVED** [review]
Code review LGTM

**Comment by CetmixGitDrone** [comment]
This PR has the `approved` label and has been created more than 5 days ago. It should therefore be ready to merge by a maintainer (or a PSC member if the concerned addon has no declared maintainer). 🤖

**Comment by CetmixGitDrone** [comment]
What a great day to merge this nice PR. Let's do it!
Prepared branch [14.0-dev-ocabot-merge-pr-59-by-ivs-cetmix-bump-nobump](https://github.com/cetmix/cetmix-tower/commits/14.0-dev-ocabot-merge-pr-59-by-ivs-cetmix-bump-nobump), awaiting test results.

**Comment by CetmixGitDrone** [comment]
Congratulations, your PR was merged at 5f15d2201b40563c1556a63f4da84a504d4b79b3. Thanks a lot for contributing to cetmix. ❤️

**Pull request merged**
