### PR TITLE
[14.0][IMP] cetmix_tower_server File Template references

### PR DESCRIPTION
**Pull request by ivs-cetmix**
Add reference support for File Templates.
Allows to refer File Templates easy way in various automation flows as well export/import them eg in yaml.

### CODE REVIEW

**Review by GabbasovDinar — APPROVED** [review]

**Review by Aldeigja — APPROVED** [review]
Functional LGTM
@ivs-cetmix Don't you like idea of adding reference field optional = show to the list view  right away?

**Comment by ivs-cetmix** [comment]
> Functional LGTM @ivs-cetmix Don't you like idea of adding reference field optional = show to the list view right away?

Sounds reasonable @Aldeigja, thank you!

**Comment by CetmixGitDrone** [comment]
What a great day to merge this nice PR. Let's do it!
Prepared branch [14.0-dev-ocabot-merge-pr-106-by-ivs-cetmix-bump-nobump](https://github.com/cetmix/cetmix-tower/commits/14.0-dev-ocabot-merge-pr-106-by-ivs-cetmix-bump-nobump), awaiting test results.

**Comment by CetmixGitDrone** [comment]
Congratulations, your PR was merged at 9b3547736314d568e2ec40e8a17e5af6358248e1. Thanks a lot for contributing to cetmix. ❤️

**Pull request merged**
